apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-b7e4"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-b7e4"
  template:
    metadata:
      labels:
        app: "myakscluster-b7e4"
    spec:
      containers:
        - name: "myakscluster-b7e4"
          image: "docker.io/kalana.azurecr.io/myakscluster"
          ports:
          - containerPort: 8082
