apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-b7e4"
    labels:
        app: "myakscluster-b7e4"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-b7e4"